### ISSUE TITLE
"GitHubを開く" のリンク先が not found でした

### ISSUE THREAD

**Issue by nwtgck** [nuta/operating-system-in-1000-lines#1]
はじめまして。

以下のリンク先が not found でした。
https://github.com/nuta/operating-system-in-1000-lines/blob/d38189d773bd35624e29ad4a4eee30e6ad17a5ce/website/app/%5Blang%5D/%5B%5B...slug%5D%5D/layout.tsx#L104

**Comment by nuta** [comment]
ありがとうございます！修正しました😃
