### ISSUE TITLE
getcharを追加する際、`user.h`にも追記する

### ISSUE THREAD

**Issue by takatama** [nuta/operating-system-in-1000-lines#10]
[文字入力システムコール (getchar)](https://operating-system-in-1000-lines.vercel.app/ja/system-call#%E6%96%87%E5%AD%97%E5%85%A5%E5%8A%9B%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%82%B3%E3%83%BC%E3%83%AB-getchar)で`user.h`に`int getchar(void);`を追記するよう記載していただくと、コンパイルが通るようになるので助かります。

**Comment by nuta** [comment]
ありがとうございます！追記しました 👍
