### ISSUE TITLE
QEMUが起動しません。

### ISSUE THREAD

**Issue by m1goh** [nuta/operating-system-in-1000-lines#2]
WSLのUbuntu22.04でQEMUが起動しません。半日程格闘してみましたが駄目でした。
もし教えていただけるようでしたら教えていただけるとありがたいです。よろしくお願いします。

こんな感じです。
'+ QEMU=qemu-system-riscv32
+ qemu-system-riscv32 -machine virt -bios default -nographic -serial mon:stdio --no-reboot
qemu-system-riscv32: Unable to load the RISC-V firmware "opensbi-riscv32-generic-fw_dynamic.bin"
akiyoshi@beetle:~/os-1000$ cat run.sh
#!/bin/bash
set -xue'

'# QEMUのファイルパス
QEMU=qemu-system-riscv32'

'# QEMUを起動'
'$QEMU -machine virt -bios default -nographic -serial mon:stdio --no-rebootakiyoshi@beetle:~/os-1000$'

**Comment by nuta** [comment]
ご報告ありがとうございます。UbuntuのQEMUパッケージだとOpenSBIの起動イメージが省かれているようです。次のURLからダウンロードすれば起動するはずです。

```
apt install -y curl
curl -LO https://github.com/qemu/qemu/raw/v8.0.4/pc-bios/opensbi-riscv32-generic-fw_dynamic.bin
```

**Comment by m1goh** [comment]
nutaさん、ありがとうございました。
無事、OpenSBIが起動できました。

**Comment by nuta** [comment]
@m1goh よかったです！こちらこそご報告ありがとうございました 😄
