### ISSUE TITLE
ファイルサイズの計算誤り

### ISSUE THREAD

**Issue by banban9999** [nuta/operating-system-in-1000-lines#21]
大変勉強になる資料をありがとうございます🙇 
下記がおそらく誤っているかと思いましたので、issue を立てさせていただきました。

https://github.com/nuta/operating-system-in-1000-lines/blob/cbdd9dbe1fd26c10acd2c467b3879f74328216f1/website/contents/ja/13-application.mdx#L165-L166

python3 -c 'print(int("10260", 16)) の実行結果は 66144 になるかと思います。

ただ、この 66144 は `shell.bin.o` のファイルサイズである 66836 と一致しないため、他の箇所も修正が必要かと思います。
(私の方でも少し調べてみましたが、一致しない理由はわかりませんでした。)

なお、私の環境 (Ubuntu 22.04.1 LTS) でも、`_binary_shell_bin_size` は  `shell.bin` のファイルサイズとは一致しますが、`shell.bin.o` とは異なる値になっていました。
```
$ llvm-nm shell.bin.o
000102bc D _binary_shell_bin_end
000102bc A _binary_shell_bin_size
00000000 D _binary_shell_bin_start

$ ls -la | grep shell.bin
-rwxrwxr-x 1 ubuntu ubuntu  66236 Oct 22 15:00 shell.bin
-rwxrwxr-x 1 ubuntu ubuntu  66604 Oct 22 15:00 shell.bin.o

$ python3 -c 'print(int("000102bc", 16))'
66236 # shell.bin のファイルサイズと一致
```

**Comment by nuta** [comment]
鋭いご指摘ありがとうございます。おっしゃる通り`shell.bin`の間違いです！修正しておきます 👍
