### ISSUE TITLE
メモリ割り当てのテストで`PAGE_SIZE`が未定義

### ISSUE THREAD

**Issue by takatama** [nuta/operating-system-in-1000-lines#5]
[メモリ割り当てのテスト](https://operating-system-in-1000-lines.vercel.app/ja/memory-allocation#%E3%83%A1%E3%83%A2%E3%83%AA%E5%89%B2%E3%82%8A%E5%BD%93%E3%81%A6%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88)の`kernel.c`ですが、`PAGE_SIZE`が未定義でした。

```console
kernel.c:131:23: error: use of undeclared identifier 'PAGE_SIZE'
    next_paddr += n * PAGE_SIZE;
                      ^
kernel.c:136:35: error: use of undeclared identifier 'PAGE_SIZE'
    memset((void *) paddr, 0, n * PAGE_SIZE);
```

`common.h`に追加たところ、正しくコンパイルして動作しました。

```c:common.h
#define PAGE_SIZE 4096
```

**Comment by nuta** [comment]
ありがとうございます！修正しました 😄
