### ISSUE TITLE
`アプリケーションのビルド`の`run.sh`で`OBJCOPY`が未定義

### ISSUE THREAD

**Issue by takatama** [nuta/operating-system-in-1000-lines#8]
[アプリケーションのビルド](https://operating-system-in-1000-lines.vercel.app/ja/application#%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89)で説明される`run.sh`で`OBJCOPY`の定義が不足しています。

私はMacBookAir(M1, 2020)を使っていますが、以下を追加する必要がありました。

```
OBJCOPY=/opt/homebrew/opt/llvm/bin/llvm-objcopy
```

**Comment by nuta** [comment]
修正しました 👍 ありがとうございます！
