### ISSUE TITLE
13章、14章の時点では`user.c`の`putchar`が存在しないためビルドに失敗する

### ISSUE THREAD

**Issue by takatama** [nuta/operating-system-in-1000-lines#9]
13章 [アプリケーション](https://operating-system-in-1000-lines.vercel.app/ja/application)、14章 [ユーザーモード](https://operating-system-in-1000-lines.vercel.app/ja/user-mode)の段階では、`user.c`の`putchar`が存在しないため、ビルドに失敗します。

```console
% ./run.sh
+ QEMU=/opt/homebrew/bin/qemu-system-riscv32
+ CC=/opt/homebrew/opt/llvm/bin/clang
+ CFLAGS='-std=c11 -O2 -g3 -Wall -Wextra --target=riscv32 -ffreestanding -nostdlib'
+ /opt/homebrew/opt/llvm/bin/clang -std=c11 -O2 -g3 -Wall -Wextra --target=riscv32 -ffreestanding -nostdlib -Wl,-Tuser.ld -Wl,-Map=shell.map -o shell.elf shell.c user.c common.c
ld.lld: error: undefined symbol: putchar
>>> referenced by common.c:13 (/Users/bx1039574/dev/os-in-1000-lines/common.c:13)
>>>               /var/folders/kr/wbzm614n24s83_grljn666k00000gq/T/common-47c591.o:(printf)
>>> referenced by common.c:14 (/Users/bx1039574/dev/os-in-1000-lines/common.c:14)
>>>               /var/folders/kr/wbzm614n24s83_grljn666k00000gq/T/common-47c591.o:(printf)
>>> referenced by common.c:0 (/Users/bx1039574/dev/os-in-1000-lines/common.c:0)
>>>               /var/folders/kr/wbzm614n24s83_grljn666k00000gq/T/common-47c591.o:(printf)
>>> referenced 8 more times
clang-16: error: ld.lld command failed with exit code 1 (use -v to see invocation)
```

 15章まで進めば、`user.c`に`putchar`が定義されるためビルドが成功します。ただ、13章で`shell.elf`の逆アセンブリを見たり、14章で動作を確認するよう説明していただいているので、13章の時点でビルドが成功できると嬉しいです。

**Comment by nuta** [comment]
鋭いご指摘ありがとうございます！修正しました 😃

**Comment by feinersaft** [comment]
What have you done to prevent this from reoccurring? I still got the error message when running the commands on chapter 05.

**Comment by nuta** [comment]
@feinersaft `putchar` in chapter 5 is for kernel, not userland (`user.c`) as reported here. Perhaps you forgot to add this definition?

https://github.com/nuta/operating-system-in-1000-lines/blob/9844a36f247f608f37ed8fef0a5401737200fe17/website/en/05-hello-world.md?plain=1#L39-L41
